### PR TITLE
ActionBar

### PR DESCRIPTION
**Pull request by Serverplayer**
Will add an ActionBar.java to send an ActionBar to a Player

### CODE REVIEW

**Comment by TheRealJasmin** [comment]
Your imports make your code version dependet, so its useless for this project. Please use reflections then your changes may probably get merged.

Regards
- jasmin

**Comment by Serverplayer** [comment]
The code of Bungeecord was the ChatColor API by md_5, but I will remove this. I dont know what you mean with "Please use Reflections", how can I use Reflections in imports?

**Comment by TheRealJasmin** [comment]
Imports like this https://github.com/Serverplayer/Community/commit/a03f7f8c1335cb1de58119b5f744ef236e0648d2#diff-dc257a2f4f715ab1b1f6c5722b7d9faeR4 will break when anybody is using anoher version.

For example here https://github.com/Janhektor/Community/blob/master/src/de/janhektor/community/utils/NBTHelper.java you can see how tu use Reflections. You will need it e.g. for CraftPlayer (just look at the sources, there are several examples).

Regards
- Jasmin

**Comment by AlexDigital** [comment]
A method for sending an actionbar packet already exists ...
https://github.com/Janhektor/Community/blob/master/src/de/janhektor/community/utils/TabActionTitle.java#L14

**Comment by Janhektor** [comment]
Hi Serverplayer!

Sorry, but there is already a class / method to work with the action bar.
Furthermore, your class is version-depend - if somebody uses another Spigot-Version, it will cause problems.

However, thanks for your work.
It's cool that you're interested in this project.

Greetings,
Janhektor

**Pull request closed without merging**
