### PR TITLE
[+] InfoLayout

### PR DESCRIPTION
**Pull request by Rincewind34**
I've added an class to handle chat messages displaying an info like a summery of commands

### CODE REVIEW

**Comment by dommi2212** [comment]
Nobody can say, *I* didn't read the readme:
"It's allowed, but not required to declare interface methods with addtional public abstract"

All Methods in an interface are "public abstract"

**Comment by Janhektor** [comment]
Yes, it's okay.
"It's allowed, but not required [...]" --- he is able to do that, but it's also allowed to work without public abstract.

**Comment by Janhektor** [comment]
Hi Rincewind!

Your pull request will be merged.

**Comment by dommi2212** [comment]
Yeah... But the first Commit only did this ^^
That's, what I wanted to point out...

**Pull request merged**
