### PR TITLE
  Edit FileManager "super class", ListenerBundle + Manager support

### PR DESCRIPTION
**Pull request by DeltaCoding**
- I simply integrated the code of Janhektor's ListenerBundle + Manager for later use.

  Code not(!) written by me, taken of Janhektors tutorial on that

- Created FileManager super class for future config managers

### CODE REVIEW

**Comment by Janhektor** [comment]
Hi DeltaCoding!

Thanks for you effort.
But unfortunately your pull request was reject.
The reason(s): We already have a location manager, my file-manager need some improvements and I've an improved ListenerBundle which will be integrated soon.

However, I appreciate your interest in this project.
If you have fun and want to help us - do it!

Regards,
Janhektor

**Comment by DeltaCoding** [comment]
Hello,

No problem, but I think you understood me wrong. The FileManager contains the save(); reload(); createFile(); from LocationManager, I moved them into a class, which can be extended by various Managers (e.g. LocationM., GeneralConfigM., ...) ;D

Greetings

**Comment by Janhektor** [comment]
Ohh, sorry, of course.
But I still have another ListenerBundle and a plan for the next (or later) tutorial which provides a FileManager :/

**Comment by DeltaCoding** [comment]
It's okay, I think the code could be better as well ^^. I don't want to "steal" your content for your videos, I think you will solve this much better ;)

**Pull request closed without merging**
