### PR TITLE
[*] Fixed typo in properties file, [*] Removed @Author, [+] Test system, [+] Achievement system

### PR DESCRIPTION
**Pull request by AlexDigital**
I added a test system to make tests with classes like the NBTHelper.
To enable tests you must set the member testsEnabled in Main.java to true.
An example for a test is in the tests package (TestNBTHelper.java).

### CODE REVIEW

**Comment by AlexDigital** [comment]
Merged it, so it can be automatically merged. :D

**Comment by Janhektor** [comment]
Hi Alex!

Your test-system is a great idea, something like a lightweight edition of JUnit.
But it would be greater, if you observe our code-style guidelines everywhere.
There are some lines of code where you forget it.
Example:
<code>
for(Annotation annotation : annotations) {
</code>
<i>(TestManager : 38)</i>

If you improve it, I'll merge your pull request.

Regards,
Janhektor

**Comment by AlexDigital** [comment]
I added my achievement system, so we can make achievements easily :D

**Comment by Janhektor** [comment]
Good idea!
But originally it was planned to store achievements, scores, etc. in a MySQL database.
If possible, I prefer to use your achievement system without file storage. It will be great if you add an interface with some methods (load, save, ...) to store the data. I'll write the implementation later in one of my tutorial.

**Comment by Janhektor** [comment]
<b>Thank for these extensive code changes!</b>

I think it'll help us a lot in development.
Your changes cannot be auto-merged - I'll resolve conflicts soon and merge this pull request manually.

Regards,
Janhektor

**Pull request merged**
