### PR TITLE
[+] log feature Alpha (not tested yet)

### PR DESCRIPTION
**Pull request by Scriptim**
i hope this is useful, you should use it in every class to ease bug fixes

### CODE REVIEW

**Comment by AlexDigital** [comment]
Please use the de.janhektor.community package, because it is the standard.
You should test it, too. So we won't have any problems later.

**Comment by Janhektor** [comment]
Hey Scriptim!

Please rename your package as Alex already said and remove the author-note at the top of your class-file.

And one request: Please observe our code-style guidelines.
After improving your code and making some changes I'll merge your commit(s).

Regards,
Janhektor

**Comment by Scriptim** [comment]
Like I said, I can't test it... I get an exception. It's caused by the multi language feature (en) - dont know how to fix... And: It's mindless to squash all in one package. Conventions say: "<topLevelDomain>.<authorName>.<packageName>" That's one of the main elements about OOP...

**Comment by Janhektor** [comment]
The error is simple to fix: Stop your server and restart it.

About the package-conventions: Right. It's a good idea to structure the source files using packages. But we'll put all sources under <b>de.janhektor.community</b>. To keep the code structured we are using <b>subpackages</b>.

**Comment by Scriptim** [comment]
Well, but no @author tags are allowed, so there's no possibility to claim own code - I agree, when every author/dev can have his own subpackage like de.janhektor.<author>.<package>

About the error, I'll test it later  (and fix bugs etc) and push it again

**Comment by Rincewind34** [comment]
What about Googleconventions?????
Do you even care about? xD

**Comment by Scriptim** [comment]
@Rincewind34 pls explain what u mean...!?

**Comment by Janhektor** [comment]
@Rincewind34 yes ... the conventions ;)
But for this project it's very important, because we need a well-structured, clear and readable source.

**Comment by Scriptim** [comment]
@Janhektor so when u need a well-structured, clear an readable source, use multiple packages

**Comment by Scriptim** [comment]
@Janhektor btw, the error is not easy to fix, it occures every time I start the server

[21:16:22 INFO]: [Community] Enabling Community v0.0.1
[21:16:22 ERROR]: Error occurred while enabling Community v0.0.1 (Is it up to date?)
java.util.MissingResourceException: Can't find bundle for base name resources.strings, locale en
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source) ~[?:1.8.0_25]
        at java.util.ResourceBundle.getBundleImpl(Unknown Source) ~[?:1.8.0_25]
        at java.util.ResourceBundle.getBundle(Unknown Source) ~[?:1.8.0_25]
        at de.janhektor.community.Main.onEnable(Main.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by TheRealJasmin** [comment]
Please create an Issue report. This isn't the place to handle this.

**Comment by Scriptim** [comment]
what exactly does not obey the conventions?

**Comment by Scriptim** [comment]
@Janhektor pls close this pull request

**Pull request closed without merging**
