### PR TITLE
More TabActionTitle support

### PR DESCRIPTION
**Pull request by Feeliiix**
Added support for versions between 1.8 and 1.8.3

### CODE REVIEW

**Comment by Janhektor** [comment]
Hi Felix!

Sorry, your changes won't be merged.
<b>Reason</b>: You don't observe the code-style guidelines everywhere and your simplifications are useless, because short validate messages aren't even better.

Thanks for your work.
It's cool that you are interested in this project.

Janhektor

**Comment by Feeliiix** [comment]
And what is with the TabActionTitle support?

**Comment by TheRealJasmin** [comment]
You should create a new PR when you want any changes to be merged.

**Comment by Feeliiix** [comment]
You're right. Its was a fail, that there are so many commits in 1 PR.

**Pull request closed without merging**
